#!/bin/sh
PHPRC=/etc/php5/cgi/
export PHPRC
export PHP_FCGI_MAX_REQUESTS=5000
export PHP_FCGI_CHILDREN=1
exec /usr/bin/php-cgi -d open_basedir=/usr/local/share/tobehost_panel:/tmp:/usr/share/php/:/var/lib/php5/sessions -d disable_functions="" $1
