#!/bin/bash

HTTPS_HOSTS=`grep -l 443 /etc/apache2/sites-enabled/*`
HTTP_HOSTS=`grep -l 80 /etc/apache2/sites-enabled/*`
HTTP_HOSTS="$HTTP_HOSTS `grep -l 8080 /etc/apache2/sites-enabled/*`"
HTTP_HOSTS="$HTTP_HOSTS `grep -l 8090 /etc/apache2/sites-enabled/*`"

HOSTS_OK=""
HOSTS_WARN=""
HOSTS_CRIT=""
HOSTS_UNKNOWN=""

VHOSTS_IGNORE="()"

VHOSTSLIST=`grep -ih ServerName $HTTP_HOSTS | sed 's/^[\t ]*//g' | sed -e 's/^ServerName //I' | egrep -v -e $VHOSTS_IGNORE | sort | uniq`

if [ -n "$VHOSTSLIST" ]; then
	for VHOST in $VHOSTSLIST; do
		HTTP_CODE=`curl -A "check_vhosts" -m 3 -o /dev/null --silent --head --write-out '%{http_code}\n' "http://$VHOST"`
		HTTP_CODE_FAMILY=`echo $HTTP_CODE | head -c1`
		case "$HTTP_CODE_FAMILY" in
			"2")
				HOSTS_OK="$HOSTS_OK $VHOST:$HTTP_CODE"
			;;
			"3")
				HOSTS_OK="$HOSTS_OK $VHOST:$HTTP_CODE"
			;;
			"4")
				HOSTS_WARN="$HOSTS_WARN $VHOST:$HTTP_CODE"
			;;
			"5")
				HOSTS_CRIT="$HOSTS_CRIT $VHOST:$HTTP_CODE"
			;;
			*)
				HOSTS_UNKNOWN="$HOSTS_UNKNOWN $VHOST:$HTTP_CODE"
			;;
		esac

	done
fi

VHOSTSLIST=`grep -ih ServerName $HTTPS_HOSTS | sed 's/^[\t ]*//g' | sed -e 's/^ServerName //I' | egrep -v -e $VHOSTS_IGNORE | sort | uniq`

if [ -n "$VHOSTSLIST" ]; then
	for VHOST in $VHOSTSLIST; do
		HTTP_CODE=`curl -A "check_vhosts" -m 3 -o /dev/null --silent --insecure --head --write-out '%{http_code}\n' "https://$VHOST"`
		HTTP_CODE_FAMILY=`echo $HTTP_CODE | head -c1`
		case "$HTTP_CODE_FAMILY" in
			"2")
				HOSTS_OK="$HOSTS_OK $VHOST:$HTTP_CODE"
			;;
			"3")
				HOSTS_OK="$HOSTS_OK $VHOST:$HTTP_CODE"
			;;
			"4")
				HOSTS_WARN="$HOSTS_WARN $VHOST:$HTTP_CODE"
			;;
			"5")
				HOSTS_CRIT="$HOSTS_CRIT $VHOST:$HTTP_CODE"
			;;
			*)
				HOSTS_UNKNOWN="$HOSTS_UNKNOWN $VHOST:$HTTP_CODE"
			;;
		esac

	done
fi

if [ -n "$HOSTS_UNKNOWN" ]; then
	STATUS="3"
elif [ -n "$HOSTS_CRIT" ]; then
	STATUS="2"
elif [ -n "$HOSTS_WARN" ]; then
	STATUS="1"
else
	STATUS=0
fi

if [[ $STATUS == 0 ]]; then
	echo "OK: all vhosts"
else
	echo $HOSTS_UNKNOWN $HOSTS_CRIT $HOSTS_WARN
	#$HOSTS_OK
fi
exit $STATUS

